services:
  db:
    image: postgres:15-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_db
      ports:
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_local_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
    postgres_local_data: